### ISSUE TITLE
Updated Web UI

### ISSUE THREAD

**Issue by zigapovhe** [yako-dev/flutter-settings-ui#61]
When should we expect web support? You could take some inspirations from chrome settings. 

![google-chrome-settings-page.png](https://user-images.githubusercontent.com/21365070/110022637-7468f280-7d2c-11eb-8242-44022f49c82c.png)

**Comment by Akora-IngDKB** [comment]
Well, the package already works on the web.

And since there are no standard guidelines for Web Setting UIs, it'll be difficult coming up with a design to suit every user.
That's my opinion though.

**Comment by zigapovhe** [comment]
Doesn't work for me tho. Will check again soon.

**Comment by yadaniyil** [comment]
Web support was just added in 1.0.0-nullsafety.1 prerelease. But yea, we need to update web version of settings UI

**Comment by tofutim** [comment]
I also vote for a desktop/web version

**Comment by yadaniyil** [comment]
Hey @zigapovhe, @tofutim . There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)

**Comment by deinspanjer** [comment]
@yadaniyil I'm commenting in this issue because it pertains to what I came across.

I was evaluating my options for introducing a settings UI in my app today, and I came across your package. It looks great, but I almost missed it because pub.dev doesn't show it as being compatible with the web. I did notice that you do support the web though, so this seems to be a simple case of the pub.dev package scanner tripping up over something small.

While researching this, I came across https://github.com/juliansteenbakker/flutter_settings_ui which states it is a fork from your package (before the 2.0 refactor) and it doesn't have the same problem. It gets full marks for compatibility and static analysis.

Maybe you could take a look at how they changed it and pick up those changes to get better visibility on pub.dev?
